In [2]:
import numpy as np

In [4]:
#Question 1 
#Create a numpy array starting from 2 till 50 with a stepsize of 3.
# Start = , Stop = 30, Step Size = 2
arr = np.arange(2, 50, 3)
print('Contents of the Array : ', arr)

Contents of the Array :  [ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


In [11]:
#Question 2 : Accept two lists of 5 elements each from the user.
l1 = [int(item) for item in input("Enter the list items : ").split()] 
  
l2 = [int(item) for item in input("Enter the list items : ").split()] 
arr1 = np.array(l1)
arr2 = np.array(l2)
print(arr1)
print(arr2)

Enter the list items : 1 2 3 
Enter the list items : 4 5 6
[1 2 3]
[4 5 6]


In [18]:
#Questions 3:Write a code snippet to find the dimensions of a ndarray and its size.
arr = np.arange(6)
print(arr,", Array type : " , arr.dtype)
# Dimension : 
print('Dimension of array : ' , arr.ndim)
#size: 
print('Size of array : ' , arr.size)

[0 1 2 3 4 5] , Array type :  int32
Dimension of array :  1
Size of array :  6


In [27]:
#Questions 4: How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
arr = np.arange(6)
a_2D = arr.reshape(2,3)
a_2D

array([[0, 1, 2],
       [3, 4, 5]])

In [52]:
#Questions 4:
A = np.arange(1, 26,3).reshape(3,3)
print(A)
B = np.arange(1, 19,2).reshape(3,3)
print(B)
print('Vertical Append:', np.vstack((A, B)))
print('Horinzontal Append:', np.hstack((A, B)))

[[ 1  4  7]
 [10 13 16]
 [19 22 25]]
[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Vertical Append: [[ 1  4  7]
 [10 13 16]
 [19 22 25]
 [ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
Horinzontal Append: [[ 1  4  7  1  3  5]
 [10 13 16  7  9 11]
 [19 22 25 13 15 17]]


In [56]:
#Questions 6:How to get unique items and counts of unique items?
arr = [1, 1, 2, 2, 3, 3]
np.unique(arr)


array([1, 2, 3])